### ISSUE TITLE
Pablo draw error I recived.

### ISSUE THREAD

**Issue by Kelpermoon** [cwensley/pablodraw#100]
Platform: WinForms
Version:3.3.12.0

```
System.NotSupportedException: NotSupported_UnreadableStream
   at System.IO.BufferedStream.ReadByteSlow()
   at System.IO.BinaryReader.ReadByte()
   at Pablo.Formats.Rip.RipExtensions.ReadRipByte(BinaryReader reader)
   at Pablo.Formats.Rip.RipExtensions.ReadRipNumber(BinaryReader reader)
   at Pablo.Formats.Rip.RipExtensions.ReadRipWord(BinaryReader reader)
   at Pablo.Formats.Rip.RipExtensions.ReadRipPoint(BinaryReader reader)
   at Pablo.Formats.Rip.Commands.Line.Read(BinaryReader reader)
   at Pablo.Formats.Rip.FormatRip.Load(Stream stream, RipDocument document, RipHandler handler)
   at Pablo.Formats.Rip.RipDocument.LoadStream(Stream stream, Format format, Handler handler)
   at Pablo.Document.Load(Stream stream, Format format, Handler handler)
   at Pablo.Formats.Animated.AnimatedDocument.LoadBase(Stream stream, Format format, Handler handler)
   at Pablo.Formats.Animated.AnimatedDocument.DocumentThreadLoader.Load()
```

**Comment by cwensley** [comment]
Thanks for reporting the issue!  Do you have the .rip file you were trying to load?  Otherwise there's nothing I can really do.

**Comment by cwensley** [comment]
Closing as this needs more info.
