### ISSUE TITLE
Tried converting a PCX file to a Rip GGraphics

### ISSUE THREAD

**Issue by Kurt-Elliott-1** [cwensley/pablodraw#101]
Platform: WinForms
Version:3.3.12.0

```
System.IO.IOException: IO_SharingViolation_File, C:\Files\1\CAR.RIP
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at Pablo.Interface.Main.LoadFile(String fileName, Boolean hasSavePermissions, Boolean setFileList, Nullable`1 editMode)
   at PabloDraw.CommandHandlers.EditorCommandLine.<>c__DisplayClass5_0.<Process>b__1(Object <p0>, EventArgs <p1>)
   at Eto.PropertyStore.TriggerEvent[T](Object key, Object sender, T args)
   at Eto.Forms.Application.OnInitialized(EventArgs e)
   at Pablo.Interface.PabloApplication.OnInitialized(EventArgs e)
   at Eto.Forms.Application.Callback.OnInitialized(Application widget, EventArgs e)
   at Eto.WinForms.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run()
   at PabloDraw.CommandHandlers.EditorCommandLine.Process(ProcessCommandLineArgs args)
```

**Comment by cwensley** [comment]
Not sure how one would "convert" a PCX to a RIP Graphics format.  Pablo can't convert them, and there's no option to do so.  Did you just rename the file?
