### ISSUE TITLE
error popup when copying

### ISSUE THREAD

**Issue by neo-backwards-one** [cwensley/pablodraw#36]
# PabloDraw3.3.0-alpha1 / PabloDraw3.2.1.30610 on windows 10 (1909)

sometimes (most of the times really) copying doesn't work right away and an error popup appears instead.
unfortunately its in german and so are bits of the errorlog that i pasted below, but the important parts are in 'computer language' i guess.

pasting right after works though so the copied item is indeed in the clipboard. from the top of my head this happens the first time you ever do a copy in a session and then works as intended (not sure for how long, i remember the popup appeared sometime later again on longer sessions).

![popup](https://user-images.githubusercontent.com/78374580/106957611-81e48a00-6738-11eb-9f87-d1dd3335886a.png)

    Informationen über das Aufrufen von JIT-Debuggen
    anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.
    
    ************** Ausnahmetext **************
    System.Runtime.InteropServices.ExternalException (0x800401D0): Der angeforderte Clipboard-Vorgang war nicht erfolgreich.
       at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
       at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy)
       at System.Windows.Forms.Clipboard.SetDataObject(Object data)
       at Eto.WinForms.Forms.ClipboardHandler.Update()
       at Eto.WinForms.Forms.DataObjectHandler`2.SetData(Byte[] value, String type)
       at Eto.Forms.Clipboard.SetData(Byte[] value, String type)
       at Eto.Forms.Clipboard.SetDataStream(Stream stream, String type)
       at Pablo.Formats.Character.Actions.Block.CopyToClipboard.OnExecuted(EventArgs e) in D:\a\pablodraw\pablodraw\Source\Pablo\Formats\Character\Actions\Block\CopyToClipboard.cs:line 64
       at Eto.Forms.Command.System.Windows.Input.ICommand.Execute(Object parameter)
       at Eto.PropertyStore.CommandWrapper.Command_Execute(Object sender, EventArgs e)
       at Eto.Forms.MenuItem.OnClick(EventArgs e)
       at Eto.Forms.MenuItem.Callback.OnClick(MenuItem widget, EventArgs e)
       at Eto.WinForms.Forms.Menu.ButtonMenuItemHandler.<.ctor>b__3_0(Object sender, EventArgs e)
       at System.Windows.Forms.ToolStripItem.OnClick(EventArgs e)
       at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
       at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
       at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
       at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
       at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
       at System.Windows.Forms.ToolStrip.WndProc(Message& m)
       at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
    
    
    ************** Geladene Assemblys **************
    System.Private.CoreLib
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Private.CoreLib.dll.
    ----------------------------------------
    PabloDraw
        Assembly-Version: 3.3.0.0.
        Win32-Version: 3.3.0.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/PabloDraw.dll.
    ----------------------------------------
    Pablo
        Assembly-Version: 3.3.0.0.
        Win32-Version: 3.3.0.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/Pablo.dll.
    ----------------------------------------
    System.Text.Encoding.CodePages
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Text.Encoding.CodePages.dll.
    ----------------------------------------
    Eto.WinForms
        Assembly-Version: 2.5.0.0.
        Win32-Version: 2.5.7683.15040.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/Eto.WinForms.dll.
    ----------------------------------------
    Eto
        Assembly-Version: 2.5.0.0.
        Win32-Version: 2.5.7683.15038.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/Eto.dll.
    ----------------------------------------
    Pablo.Interface
        Assembly-Version: 3.3.0.0.
        Win32-Version: 3.3.0.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/Pablo.Interface.dll.
    ----------------------------------------
    System.ComponentModel
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.ComponentModel.dll.
    ----------------------------------------
    System.Console
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Console.dll.
    ----------------------------------------
    System.Text.RegularExpressions
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Text.RegularExpressions.dll.
    ----------------------------------------
    System.Linq
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Linq.dll.
    ----------------------------------------
    System.Collections.Concurrent
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Collections.Concurrent.dll.
    ----------------------------------------
    System.Collections
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Collections.dll.
    ----------------------------------------
    Microsoft.WindowsAPICodePack.Shell
        Assembly-Version: 1.1.0.0.
        Win32-Version: 1.1.0.0.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/Microsoft.WindowsAPICodePack.Shell.dll.
    ----------------------------------------
    Microsoft.WindowsAPICodePack
        Assembly-Version: 1.1.0.0.
        Win32-Version: 1.1.0.0.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/Microsoft.WindowsAPICodePack.dll.
    ----------------------------------------
    System.Runtime.InteropServices.RuntimeInformation
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Runtime.InteropServices.RuntimeInformation.dll.
    ----------------------------------------
    System.Linq.Expressions
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Linq.Expressions.dll.
    ----------------------------------------
    System.Windows.Forms
        Assembly-Version: 5.0.2.0.
        Win32-Version: 5.0.220.61301.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Windows.Forms.dll.
    ----------------------------------------
    System.Windows.Forms.Primitives
        Assembly-Version: 5.0.2.0.
        Win32-Version: 5.0.220.61301.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Windows.Forms.Primitives.dll.
    ----------------------------------------
    System.ComponentModel.Primitives
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.ComponentModel.Primitives.dll.
    ----------------------------------------
    System.Runtime.InteropServices
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Runtime.InteropServices.dll.
    ----------------------------------------
    System.Drawing.Primitives
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Drawing.Primitives.dll.
    ----------------------------------------
    System.Diagnostics.TraceSource
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Diagnostics.TraceSource.dll.
    ----------------------------------------
    System.Collections.Specialized
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Collections.Specialized.dll.
    ----------------------------------------
    System.ComponentModel.EventBasedAsync
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.ComponentModel.EventBasedAsync.dll.
    ----------------------------------------
    System.Drawing.Common
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.20.51904.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Drawing.Common.dll.
    ----------------------------------------
    Microsoft.Win32.Primitives
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/Microsoft.Win32.Primitives.dll.
    ----------------------------------------
    Accessibility
        Assembly-Version: 4.0.0.0.
        Win32-Version: 5.0.220.61301.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/Accessibility.dll.
    ----------------------------------------
    System.Diagnostics.Process
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Diagnostics.Process.dll.
    ----------------------------------------
    System.Private.Xml
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Private.Xml.dll.
    ----------------------------------------
    System.Runtime.CompilerServices.Unsafe
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Runtime.CompilerServices.Unsafe.dll.
    ----------------------------------------
    System.ObjectModel
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.ObjectModel.dll.
    ----------------------------------------
    System.ComponentModel.TypeConverter
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.ComponentModel.TypeConverter.dll.
    ----------------------------------------
    System.IO.FileSystem
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.IO.FileSystem.dll.
    ----------------------------------------
    Lidgren.Network
        Assembly-Version: 2012.1.7.0.
        Win32-Version: 2012.1.7.0.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/Lidgren.Network.dll.
    ----------------------------------------
    System.Collections.NonGeneric
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Collections.NonGeneric.dll.
    ----------------------------------------
    Microsoft.Win32.SystemEvents
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.20.51904.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/Microsoft.Win32.SystemEvents.dll.
    ----------------------------------------
    System.Windows.Forms.resources
        Assembly-Version: 5.0.2.0.
        Win32-Version: 5.0.220.61301.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/de/System.Windows.Forms.resources.dll.
    ----------------------------------------
    System.Threading
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Threading.dll.
    ----------------------------------------
    System.Security.Cryptography.Algorithms
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Security.Cryptography.Algorithms.dll.
    ----------------------------------------
    System.Private.Uri
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Private.Uri.dll.
    ----------------------------------------
    System.Net.Primitives
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Net.Primitives.dll.
    ----------------------------------------
    System.Diagnostics.FileVersionInfo
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Diagnostics.FileVersionInfo.dll.
    ----------------------------------------
    System.Diagnostics.StackTrace
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Diagnostics.StackTrace.dll.
    ----------------------------------------
    System.Reflection.Metadata
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Reflection.Metadata.dll.
    ----------------------------------------
    System.Collections.Immutable
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.Collections.Immutable.dll.
    ----------------------------------------
    System.IO.MemoryMappedFiles
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.IO.MemoryMappedFiles.dll.
    ----------------------------------------
    System.IO.Compression
        Assembly-Version: 5.0.0.0.
        Win32-Version: 5.0.220.61120.
        CodeBase: file:///C:/Users/CENSORED/AppData/Local/Temp/.net/PabloDraw3.3.0-alpha1/dcvnv5ca.0cc/System.IO.Compression.dll.
    ----------------------------------------
    
    ************** JIT-Debuggen **************

**Comment by cwensley** [comment]
Hm, interesting.  Thanks for reporting the issue!  I'll investigate.
