### ISSUE TITLE
3.3.0-beta1 console conversion segfault

### ISSUE THREAD

**Issue by Sembiance** [cwensley/pablodraw#56]
Using `3.3.0-beta1.tar.gz` under `Linux 5.18.8` when attempting to convert via the console the attached `test.rip` file in [test.zip](https://github.com/cwensley/pablodraw/files/9548728/test.zip) yields a segfault:

```
/tmp $ /tmp/PabloDraw --convert=/tmp/test.rip --out=/tmp/out.png
Converting '/tmp/test.rip' (rip.rip) to '/tmp/out.png' (image.png)

(process:25822): Gtk-CRITICAL **: 10:04:22.092: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(process:25822): Gtk-CRITICAL **: 10:04:22.092: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(process:25822): Gtk-CRITICAL **: 10:04:22.092: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault (core dumped)
```

Running it with `gdb` yields the following backtrace:
```
(gdb) bt
#0  0x00007fffc46da1c0 in  () at /usr/lib64/libgtk-3.so.0
#1  0x00007fffc457f314 in  () at /usr/lib64/libgtk-3.so.0
#2  0x00007fffc459fac8 in  () at /usr/lib64/libgtk-3.so.0
#3  0x00007fffc458ad8a in  () at /usr/lib64/libgtk-3.so.0
#4  0x00007fffc459f998 in  () at /usr/lib64/libgtk-3.so.0
#5  0x00007fffc458b6c2 in  () at /usr/lib64/libgtk-3.so.0
#6  0x00007fffc5d8c99b in g_type_create_instance () at /usr/lib64/libgobject-2.0.so.0
#7  0x00007fffc5d71cad in  () at /usr/lib64/libgobject-2.0.so.0
#8  0x00007fffc5d7322d in g_object_new_with_properties () at /usr/lib64/libgobject-2.0.so.0
#9  0x00007fffc5d73bd9 in g_object_new () at /usr/lib64/libgobject-2.0.so.0
#10 0x00007fffc45a823b in  () at /usr/lib64/libgtk-3.so.0
#11 0x00007fffc478d97d in  () at /usr/lib64/libgtk-3.so.0
#12 0x00007fffc5d8c99b in g_type_create_instance () at /usr/lib64/libgobject-2.0.so.0
#13 0x00007fffc5d71cad in  () at /usr/lib64/libgobject-2.0.so.0
#14 0x00007fffc5d7322d in g_object_new_with_properties () at /usr/lib64/libgobject-2.0.so.0
#15 0x00007fffc5d73bd9 in g_object_new () at /usr/lib64/libgobject-2.0.so.0
#16 0x00007fffc44b4abc in gtk_alignment_new () at /usr/lib64/libgtk-3.so.0
#17 0x00005554dbe5ee68 in  ()
#18 0x0000000000000000 in  ()
```

**Comment by Sembiance** [comment]
Just tested it with latest source code, works.

**Comment by cwensley** [comment]
Awesome, thanks for the additional testing!
