### ISSUE TITLE
Runtime issue on Fedora

### ISSUE THREAD

**Issue by fcambus** [cwensley/pablodraw#97]
Hi,

After installing the `dotnet-sdk-7.0` package, I'm attempting to build and run PabloDraw as follow:

~~~
dotnet build Source/PabloDraw/PabloDraw.csproj
dotnet run --project Source/PabloDraw/PabloDraw.csproj
~~~

Builds succeeds but I get this error at runtime when starting the program:

~~~
Platform: Gtk
Version:3.3.12.0

```
GLib.GException: Unrecognized image file format
   at Gdk.PixbufLoader.Write(Byte[] buf, UInt64 count)
   at Gdk.PixbufLoader.Write(Byte[] bytes, UInt32 count)
   at Gdk.PixbufLoader.LoadFromStream(Stream input)
   at Gdk.PixbufLoader.InitFromStream(Stream stream)
   at Gdk.PixbufLoader..ctor(Stream stream)
   at Gdk.Pixbuf..ctor(Stream stream)
   at Eto.GtkSharp.Drawing.IconHandler.Create(Stream stream)
   at Eto.Drawing.Icon..ctor(Stream stream)
   at Eto.Drawing.Icon.FromResource(String resourceName, Assembly assembly)
   at Pablo.ImageCache.IconFromResource(String resource, Assembly assembly) in /home/fcambus/pablodraw/Source/Pablo/ImageCache.cs:line 21
   at Pablo.Interface.Main..ctor() in /home/fcambus/pablodraw/Source/Pablo.Interface/Main.cs:line 395
   at Pablo.Interface.PabloApplication.OnInitialized(EventArgs e) in /home/fcambus/pablodraw/Source/Pablo.Interface/PabloApplication.cs:line 49
   at Eto.Forms.Application.Callback.OnInitialized(Application widget, EventArgs e)
   at Eto.GtkSharp.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run()
   at PabloDraw.CommandHandlers.EditorCommandLine.Process(ProcessCommandLineArgs args) in /home/fcambus/pablodraw/Source/PabloDraw/CommandHandlers/EditorCommandLine.cs:line 80
```
~~~

I don't know much about the .NET ecosystem so I might be missing something obvious.

Here is information about the build environment used:

~~~
.NET SDK:
 Version:   7.0.111
 Commit:    06c8b346e4

Runtime Environment:
 OS Name:     fedora
 OS Version:  38
 OS Platform: Linux
 RID:         fedora.38-x64
 Base Path:   /usr/lib64/dotnet/sdk/7.0.111/

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  7.0.111 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.11 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.11 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib64/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
~~~

**Comment by cwensley** [comment]
This should work with the latest code, using .NET 9 sdk.

**Comment by fcambus** [comment]
I tried again with the .NET 9.0 SDK and unfortunately I still get the same error when launching the program:

~~~
Platform: Gtk
Version:3.3.14.0

```
GLib.GException: Unrecognized image file format
   at Gdk.PixbufLoader.Write(Byte[] buf, UInt64 count)
   at Gdk.PixbufLoader.Write(Byte[] bytes, UInt32 count)
   at Gdk.PixbufLoader.LoadFromStream(Stream input)
   at Gdk.PixbufLoader.InitFromStream(Stream stream)
   at Gdk.PixbufLoader..ctor(Stream stream)
   at Gdk.Pixbuf..ctor(Stream stream)
   at Eto.GtkSharp.Drawing.IconHandler.Create(Stream stream)
   at Eto.Drawing.Icon..ctor(Stream stream)
   at Eto.Drawing.Icon.FromResource(String resourceName, Assembly assembly)
   at Pablo.ImageCache.IconFromResource(String resource, Assembly assembly) in /home/fcambus/pablodraw/Source/Pablo/ImageCache.cs:line 21
   at Pablo.Interface.Main..ctor() in /home/fcambus/pablodraw/Source/Pablo.Interface/Main.cs:line 395
   at Pablo.Interface.PabloApplication.OnInitialized(EventArgs e) in /home/fcambus/pablodraw/Source/Pablo.Interface/PabloApplication.cs:line 49
   at Eto.Forms.Application.Callback.OnInitialized(Application widget, EventArgs e)
   at Eto.GtkSharp.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run()
   at PabloDraw.CommandHandlers.EditorCommandLine.Process(ProcessCommandLineArgs args) in /home/fcambus/pablodraw/Source/PabloDraw/CommandHandlers/EditorCommandLine.cs:line 83
```
~~~

There is also another error:

~~~
Platform: Gtk
Version:3.3.14.0

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Pablo.Interface.Dialogs.FileModifiedDialog.ShowDialog() in /home/fcambus/pablodraw/Source/Pablo.Interface/Dialogs/FileModifiedDialog.cs:line 23
   at Pablo.Interface.Dialogs.FileModifiedDialog.Show(Main main) in /home/fcambus/pablodraw/Source/Pablo.Interface/Dialogs/FileModifiedDialog.cs:line 18
   at Pablo.Interface.PabloApplication.OnTerminating(CancelEventArgs e) in /home/fcambus/pablodraw/Source/Pablo.Interface/PabloApplication.cs:line 64
   at Eto.Forms.Application.Callback.OnTerminating(Application widget, CancelEventArgs e)
   at Eto.GtkSharp.Forms.GtkWindow`3.CloseWindow(Action`1 closing)
   at Eto.GtkSharp.Forms.DialogHandler.ShowModal()
   at Eto.Forms.Dialog.ShowModal()
   at PabloDraw.CommandHandlers.EditorCommandLine.<>c__DisplayClass7_0.<ShowErrorDialog>b__0() in /home/fcambus/pablodraw/Source/PabloDraw/CommandHandlers/EditorCommandLine.cs:line 142
   at Eto.GtkSharp.Forms.ApplicationHandler.Invoke(Action action)
   at Eto.Forms.Application.Invoke(Action action)
   at PabloDraw.CommandHandlers.EditorCommandLine.ShowErrorDialog(Object exceptionObject) in /home/fcambus/pablodraw/Source/PabloDraw/CommandHandlers/EditorCommandLine.cs:line 109
   at PabloDraw.CommandHandlers.EditorCommandLine.Process(ProcessCommandLineArgs args) in /home/fcambus/pablodraw/Source/PabloDraw/CommandHandlers/EditorCommandLine.cs:line 87
   at PabloDraw.Program.Run() in /home/fcambus/pablodraw/Source/PabloDraw/Program.cs:line 42
   at PabloDraw.Startup.Main() in /home/fcambus/pablodraw/Source/PabloDraw/Startup.cs:line 11
```
~~~

**Comment by cwensley** [comment]
Hm, sounds like you might be missing some dependency to be able to load .ico files with gtk..
